/* This file was generated by the Hex-Rays decompiler version 8.4.0.240320.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_1020();
void sub_1030();
void sub_1040();
void sub_1050();
void sub_1060();
void sub_1070();
void sub_1080();
void sub_1090();
// int __fastcall _cxa_finalize(void *);
// int puts(const char *s);
// size_t strlen(const char *s);
// int printf(const char *format, ...);
// size_t strcspn(const char *s, const char *reject);
// char *fgets(char *s, int n, FILE *stream);
// int setvbuf(FILE *stream, char *buf, int modes, size_t n);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
void *deregister_tm_clones();
__int64 register_tm_clones();
void *_do_global_dtors_aux();
__int64 frame_dummy(); // weak
int __fastcall main(int argc, const char **argv, const char **envp);
unsigned __int64 init();
_BOOL8 __fastcall check_message(const char *a1);
void term_proc();
// int __fastcall _libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int __fastcall __cxa_finalize(void *);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

void *_dso_handle = &_dso_handle; // idb
_UNKNOWN _bss_start; // weak
FILE *stdout; // idb
FILE *stdin; // idb
char completed_0; // weak
_BYTE flag[160]; // weak


//----- (0000000000001000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 4138: using guessed type __int64 _gmon_start__(void);

//----- (0000000000001020) ----------------------------------------------------
void sub_1020()
{
  JUMPOUT(0LL);
}
// 1026: control flows out of bounds to 0

//----- (0000000000001030) ----------------------------------------------------
void sub_1030()
{
  sub_1020();
}

//----- (0000000000001040) ----------------------------------------------------
void sub_1040()
{
  sub_1020();
}

//----- (0000000000001050) ----------------------------------------------------
void sub_1050()
{
  sub_1020();
}

//----- (0000000000001060) ----------------------------------------------------
void sub_1060()
{
  sub_1020();
}

//----- (0000000000001070) ----------------------------------------------------
void sub_1070()
{
  sub_1020();
}

//----- (0000000000001080) ----------------------------------------------------
void sub_1080()
{
  sub_1020();
}

//----- (0000000000001090) ----------------------------------------------------
void sub_1090()
{
  sub_1020();
}

//----- (0000000000001120) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (__fastcall *)(int, char **, char **))main, v4, &retaddr, 0LL, 0LL, a3, &v5);
  __halt();
}
// 112A: positive sp value 8 has been found
// 1131: variable 'v3' is possibly undefined

//----- (0000000000001150) ----------------------------------------------------
void *deregister_tm_clones()
{
  return &_bss_start;
}

//----- (0000000000001180) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0LL;
}

//----- (00000000000011C0) ----------------------------------------------------
void *_do_global_dtors_aux()
{
  void *result; // rax

  if ( !completed_0 )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(_dso_handle);
    result = deregister_tm_clones();
    completed_0 = 1;
  }
  return result;
}
// 4038: using guessed type char completed_0;

//----- (0000000000001200) ----------------------------------------------------
__int64 frame_dummy()
{
  return register_tm_clones();
}
// 1200: using guessed type __int64 frame_dummy();

//----- (0000000000001209) ----------------------------------------------------
int __fastcall main(int argc, const char **argv, const char **envp)
{
  char s[152]; // [rsp+10h] [rbp-A0h] BYREF
  unsigned __int64 v5; // [rsp+A8h] [rbp-8h]

  v5 = __readfsqword(0x28u);
  setvbuf(stdout, 0LL, 2, 0LL);
  init();
  puts("\nThe flag is hidden nearby.\nI can help you check if you got it right!\n");
  printf("> ");
  fgets(s, 144, stdin);
  s[strcspn(s, "\n")] = 0;
  if ( check_message(s) )
  {
    puts("\nNice Job! You got it!");
    puts("Can you read it?\n\n");
    return 0;
  }
  else
  {
    puts("\nNah! That doesn't look like the flag!\n");
    return 1;
  }
}
// 1209: using guessed type char s[152];

//----- (000000000000131D) ----------------------------------------------------
unsigned __int64 init()
{
  int i; // [rsp+8h] [rbp-98h]
  int j; // [rsp+Ch] [rbp-94h]
  __int64 v3[16]; // [rsp+10h] [rbp-90h] BYREF
  unsigned __int64 v4; // [rsp+98h] [rbp-8h]
  __int64 savedregs; // [rsp+A0h] [rbp+0h] BYREF

  v4 = __readfsqword(0x28u);
  qmemcpy(
    v3,
    "Y3Nhd2N0ZntOM3Yzcl9wcjA3M2M3X3MzbnMxNzF2M18xbmYwcm00NzEwbl91czFuZ19qdXM3XzNuYzBkMW5nIV8jM25jMGQxbmdfMXNfbjB0XzNuY3J5cDcxMG4hfQ==",
    sizeof(v3));
  for ( i = 0; i <= 15; ++i )
  {
    for ( j = 0; j <= 7; ++j )
      flag[8 * i + j] = *((_BYTE *)&savedregs + 8 * i + j - 144);
  }
  return v4 - __readfsqword(0x28u);
}
// 4040: using guessed type _BYTE flag[160];

//----- (00000000000014BA) ----------------------------------------------------
_BOOL8 __fastcall check_message(const char *a1)
{
  int i; // [rsp+18h] [rbp-8h]
  int j; // [rsp+1Ch] [rbp-4h]

  for ( i = 0; i <= 15; ++i )
  {
    for ( j = 0; j <= 7; ++j )
    {
      if ( a1[8 * i + (__int64)j] != flag[8 * i + j] )
        return 0LL;
    }
  }
  return strlen(a1) == 128;
}
// 4040: using guessed type _BYTE flag[160];

//----- (0000000000001558) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=36 queued=18 decompiled=18 lumina nreq=0 worse=0 better=0
// ALL OK, 18 function(s) have been successfully decompiled
